/*
 * Copyright 2017 NUROX Ltd.
 *
 * Licensed under the NUROX Ltd Software License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.looseboxes.com/legal/licenses/software.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.doctracker.basic.ui;

import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;

/**
 *
 * @author Josh
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPanelScrollPane = new javax.swing.JScrollPane();
        searchPanel = new com.doctracker.basic.ui.SearchPanel();
        searchResultsPanel = new com.doctracker.basic.ui.SearchResultsPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newtaskMenuItem = new javax.swing.JMenuItem();
        refreshMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        printMenuItem = new javax.swing.JMenuItem();
        importMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        sqlMenu = new javax.swing.JMenu();
        executeSelectMenuItem = new javax.swing.JMenuItem();
        executeUpdateMenuItem = new javax.swing.JMenuItem();
        executeDeleteMenuItem = new javax.swing.JMenuItem();
        outputMenu = new javax.swing.JMenu();
        refreshOutputMenuItem = new javax.swing.JMenuItem();
        selectFolderMenuItem = new javax.swing.JMenuItem();
        fontSizeMenuItem = new javax.swing.JMenuItem();
        remoteMenu = new javax.swing.JMenu();
        syncMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        searchPanelScrollPane.setViewportView(searchPanel);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        newtaskMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newtaskMenuItem.setMnemonic('o');
        newtaskMenuItem.setText("New Task");
        fileMenu.add(newtaskMenuItem);

        refreshMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        refreshMenuItem.setText("Refresh");
        fileMenu.add(refreshMenuItem);

        saveAsMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        printMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        printMenuItem.setText("Print");
        fileMenu.add(printMenuItem);

        importMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        importMenuItem.setText("Import");
        fileMenu.add(importMenuItem);

        exitMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        sqlMenu.setText("SQL");
        sqlMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        executeSelectMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        executeSelectMenuItem.setText("Execute SELECT");
        sqlMenu.add(executeSelectMenuItem);

        executeUpdateMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        executeUpdateMenuItem.setText("Execute UPDATE");
        executeUpdateMenuItem.setEnabled(false);
        sqlMenu.add(executeUpdateMenuItem);

        executeDeleteMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        executeDeleteMenuItem.setText("Execute DELETE");
        executeDeleteMenuItem.setEnabled(false);
        sqlMenu.add(executeDeleteMenuItem);

        menuBar.add(sqlMenu);

        outputMenu.setText("Output");
        outputMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        refreshOutputMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        refreshOutputMenuItem.setText("Refresh");
        outputMenu.add(refreshOutputMenuItem);

        selectFolderMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        selectFolderMenuItem.setText("Select Folder");
        outputMenu.add(selectFolderMenuItem);

        fontSizeMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fontSizeMenuItem.setText("Font Size");
        outputMenu.add(fontSizeMenuItem);

        menuBar.add(outputMenu);

        remoteMenu.setText("Remote");
        remoteMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        syncMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        syncMenuItem.setText("Sync");
        remoteMenu.add(syncMenuItem);

        menuBar.add(remoteMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");
        helpMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        aboutMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchPanelScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
            .addComponent(searchResultsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchPanelScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchResultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem executeDeleteMenuItem;
    private javax.swing.JMenuItem executeSelectMenuItem;
    private javax.swing.JMenuItem executeUpdateMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fontSizeMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem importMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newtaskMenuItem;
    private javax.swing.JMenu outputMenu;
    private javax.swing.JMenuItem printMenuItem;
    private javax.swing.JMenuItem refreshMenuItem;
    private javax.swing.JMenuItem refreshOutputMenuItem;
    private javax.swing.JMenu remoteMenu;
    private javax.swing.JMenuItem saveAsMenuItem;
    private com.doctracker.basic.ui.SearchPanel searchPanel;
    private javax.swing.JScrollPane searchPanelScrollPane;
    private com.doctracker.basic.ui.SearchResultsPanel searchResultsPanel;
    private javax.swing.JMenuItem selectFolderMenuItem;
    private javax.swing.JMenu sqlMenu;
    private javax.swing.JMenuItem syncMenuItem;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getAboutMenuItem() {
        return aboutMenuItem;
    }

    public JMenuItem getExitMenuItem() {
        return exitMenuItem;
    }

    public JMenu getFileMenu() {
        return fileMenu;
    }

    public JMenu getHelpMenu() {
        return helpMenu;
    }

//    public JMenuBar getMenuBar() {
//        return menuBar;
//    }

    public JMenuItem getOpenMenuItem() {
        return newtaskMenuItem;
    }

    public JMenuItem getSaveAsMenuItem() {
        return saveAsMenuItem;
    }

    public SearchResultsPanel getSearchResultsPanel() {
        return searchResultsPanel;
    }

    public JMenuItem getNewtaskMenuItem() {
        return newtaskMenuItem;
    }

    public JMenuItem getRefreshMenuItem() {
        return refreshMenuItem;
    }

    public SearchPanel getSearchPanel() {
        return searchPanel;
    }

    public JScrollPane getSearchPanelScrollPane() {
        return searchPanelScrollPane;
    }

    public JMenuItem getImportMenuItem() {
        return importMenuItem;
    }

    public JMenuItem getPrintMenuItem() {
        return printMenuItem;
    }

    public JMenuItem getExecuteDeleteMenuItem() {
        return executeDeleteMenuItem;
    }

    public JMenuItem getExecuteSelectMenuItem() {
        return executeSelectMenuItem;
    }

    public JMenuItem getExecuteUpdateMenuItem() {
        return executeUpdateMenuItem;
    }

    public JMenu getSqlMenu() {
        return sqlMenu;
    }

    public JMenuItem getFontSizeMenuItem() {
        return fontSizeMenuItem;
    }

    public JMenu getOutputMenu() {
        return outputMenu;
    }

    public JMenuItem getSelectFolderMenuItem() {
        return selectFolderMenuItem;
    }

    public JMenuItem getRefreshOutputMenuItem() {
        return refreshOutputMenuItem;
    }

    public JMenu getRemoteMenu() {
        return remoteMenu;
    }

    public JMenuItem getSyncMenuItem() {
        return syncMenuItem;
    }
}
