/*
 * Copyright 2017 NUROX Ltd.
 *
 * Licensed under the NUROX Ltd Software License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.looseboxes.com/legal/licenses/software.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.doctracker.basic.ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 * @author Josh
 */
public class SearchResultsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchResultsPanel
     */
    public SearchResultsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        searchResultsTable = new javax.swing.JTable();
        previousPageButton = new javax.swing.JButton();
        nextPageButton = new javax.swing.JButton();
        paginationLabel = new javax.swing.JLabel();
        firstPageButton = new javax.swing.JButton();
        lastPageButton = new javax.swing.JButton();
        addTaskButton = new javax.swing.JButton();

        setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setPreferredSize(new java.awt.Dimension(570, 512));

        scrollPane.setPreferredSize(new java.awt.Dimension(600, 300));

        searchResultsTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        searchResultsTable.setMaximumSize(new java.awt.Dimension(32767, 32767));
        searchResultsTable.setPreferredSize(new java.awt.Dimension(600, 500));
        scrollPane.setViewportView(searchResultsTable);

        previousPageButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        previousPageButton.setText("<");

        nextPageButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nextPageButton.setText(">");

        paginationLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paginationLabel.setPreferredSize(new java.awt.Dimension(186, 31));

        firstPageButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        firstPageButton.setText("<<");

        lastPageButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lastPageButton.setText(">>");

        addTaskButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addTaskButton.setText("Add Task");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addTaskButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstPageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previousPageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paginationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextPageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastPageButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextPageButton)
                            .addComponent(lastPageButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(previousPageButton)
                            .addComponent(firstPageButton)
                            .addComponent(addTaskButton)))
                    .addComponent(paginationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTaskButton;
    private javax.swing.JButton firstPageButton;
    private javax.swing.JButton lastPageButton;
    private javax.swing.JButton nextPageButton;
    private javax.swing.JLabel paginationLabel;
    private javax.swing.JButton previousPageButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable searchResultsTable;
    // End of variables declaration//GEN-END:variables

    public JScrollPane getScrollPane() {
        return scrollPane;
    }

    public JTable getSearchResultsTable() {
        return searchResultsTable;
    }

    public JButton getNextPageButton() {
        return nextPageButton;
    }

    public JLabel getPaginationLabel() {
        return paginationLabel;
    }

    public JButton getPreviousPageButton() {
        return previousPageButton;
    }

    public JButton getFirstPageButton() {
        return firstPageButton;
    }

    public JButton getLastPageButton() {
        return lastPageButton;
    }

    public JButton getAddTaskButton() {
        return addTaskButton;
    }
}
