/*
 * Copyright 2017 NUROX Ltd.
 *
 * Licensed under the NUROX Ltd Software License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.looseboxes.com/legal/licenses/software.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.doctracker.basic.ui;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Josh
 */
public class TaskPanelInternal extends javax.swing.JPanel {

    /**
     * Creates new form Aaa
     */
    public TaskPanelInternal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        referencenumberTextField = new javax.swing.JTextField();
        referencenumberLabel = new javax.swing.JLabel();
        subjectTextField = new javax.swing.JTextField();
        datesignedPanel = new com.doctracker.basic.ui.DateTimePanel();
        subjectLabel = new javax.swing.JLabel();
        datesignedLabel = new javax.swing.JLabel();
        taskTextField = new javax.swing.JTextField();
        taskLabel = new javax.swing.JLabel();
        responsibilityComboBox = new javax.swing.JComboBox<>();

        referencenumberTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        referencenumberLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        referencenumberLabel.setText("Ref Number");

        subjectTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        subjectLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subjectLabel.setText("Subject");

        datesignedLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        datesignedLabel.setText("Date Signed");

        taskTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        taskLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        taskLabel.setText("Task");

        responsibilityComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        responsibilityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(taskTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(referencenumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(referencenumberLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subjectLabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datesignedLabel)
                            .addComponent(datesignedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(responsibilityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(datesignedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datesignedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(referencenumberLabel)
                            .addComponent(subjectLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(referencenumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(taskLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(responsibilityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datesignedLabel;
    private com.doctracker.basic.ui.DateTimePanel datesignedPanel;
    private javax.swing.JLabel referencenumberLabel;
    private javax.swing.JTextField referencenumberTextField;
    private javax.swing.JComboBox<String> responsibilityComboBox;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JTextField subjectTextField;
    private javax.swing.JLabel taskLabel;
    private javax.swing.JTextField taskTextField;
    // End of variables declaration//GEN-END:variables

    public JLabel getDatesignedLabel() {
        return datesignedLabel;
    }

    public DateTimePanel getDatesignedPanel() {
        return datesignedPanel;
    }

    public JLabel getReferencenumberLabel() {
        return referencenumberLabel;
    }

    public JTextField getReferencenumberTextField() {
        return referencenumberTextField;
    }

    public JComboBox<String> getResponsibilityComboBox() {
        return responsibilityComboBox;
    }

    public JLabel getSubjectLabel() {
        return subjectLabel;
    }

    public JTextField getSubjectTextField() {
        return subjectTextField;
    }

    public JLabel getTaskLabel() {
        return taskLabel;
    }

    public JTextField getTaskTextField() {
        return taskTextField;
    }
}
