/*
 * Copyright 2017 NUROX Ltd.
 *
 * Licensed under the NUROX Ltd Software License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.looseboxes.com/legal/licenses/software.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.doctracker.basic.ui;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Josh
 */
public class TaskPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewTaskPanel
     */
    public TaskPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        referencenumberLabel = new javax.swing.JLabel();
        referencenumberTextfield = new javax.swing.JTextField();
        subjectLabel = new javax.swing.JLabel();
        subjectTextfield = new javax.swing.JTextField();
        taskLabel = new javax.swing.JLabel();
        responsibilityLabel = new javax.swing.JLabel();
        responsiblityCombobox = new javax.swing.JComboBox<>();
        timeopendLabel = new javax.swing.JLabel();
        timeopenedHoursTextfield = new javax.swing.JTextField();
        timeopenedDayTextfield = new javax.swing.JTextField();
        timeopenedMonthCombobox = new javax.swing.JComboBox<>();
        deadlineLabel = new javax.swing.JLabel();
        deadlineHoursTextfield = new javax.swing.JTextField();
        deadlineDayTextfield = new javax.swing.JTextField();
        deadlineMonthCombobox = new javax.swing.JComboBox<>();
        timeopenedYearCombobox = new javax.swing.JComboBox<>();
        deadlineYearCombobox = new javax.swing.JComboBox<>();
        addTaskAndDocButton = new javax.swing.JButton();
        cleartaskButton = new javax.swing.JButton();
        timeopendHoursLabel = new javax.swing.JLabel();
        timeopendDeadlineLabel = new javax.swing.JLabel();
        deadlineExpectationLabel = new javax.swing.JLabel();
        deadlineExpectationTextfield = new javax.swing.JTextField();
        formNoteLabel = new javax.swing.JLabel();
        addTaskToDocButton = new javax.swing.JButton();
        docidLabel = new javax.swing.JLabel();
        datesignedLabel = new javax.swing.JLabel();
        datesignedDayTextfield = new javax.swing.JTextField();
        datesignedMonthCombobox = new javax.swing.JComboBox<>();
        datesignedYearCombobox = new javax.swing.JComboBox<>();
        timeopenedMinutesTextfield = new javax.swing.JTextField();
        deadlineMinutesTextfield = new javax.swing.JTextField();
        separator = new javax.swing.JSeparator();
        taskdetailsLabel = new javax.swing.JLabel();
        taskTextAreaScrollPane = new javax.swing.JScrollPane();
        taskTextArea = new javax.swing.JTextArea();

        referencenumberLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        referencenumberLabel.setText("Ref Number ");

        referencenumberTextfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        subjectLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        subjectLabel.setText("<html><span style=\"color:red\">Subject *</span></html>     ");

        subjectTextfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        taskLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taskLabel.setText("<html><span style=\"color:red\">Task *</span></html>");

        responsibilityLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        responsibilityLabel.setText("<html><span style=\"color:red\">Who *</span></html>");

        responsiblityCombobox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        responsiblityCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        timeopendLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        timeopendLabel.setText("Track Starts");
        timeopendLabel.setToolTipText("Time tracking begins. You may set this later.");

        timeopenedHoursTextfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        timeopenedDayTextfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        timeopenedMonthCombobox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        timeopenedMonthCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        deadlineLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deadlineLabel.setText("Deadline");

        deadlineHoursTextfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        deadlineDayTextfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        deadlineMonthCombobox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deadlineMonthCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        timeopenedYearCombobox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        timeopenedYearCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        deadlineYearCombobox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deadlineYearCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addTaskAndDocButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addTaskAndDocButton.setText("Add Task");
        addTaskAndDocButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cleartaskButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cleartaskButton.setText("Clear");
        cleartaskButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        timeopendHoursLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        timeopendHoursLabel.setForeground(new java.awt.Color(153, 153, 153));
        timeopendHoursLabel.setText("Hrs");
        timeopendHoursLabel.setToolTipText("Time tracking begins. You may set this later.");

        timeopendDeadlineLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        timeopendDeadlineLabel.setForeground(new java.awt.Color(153, 153, 153));
        timeopendDeadlineLabel.setText("Hrs");
        timeopendDeadlineLabel.setToolTipText("Time tracking begins. You may set this later.");

        deadlineExpectationLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deadlineExpectationLabel.setText("Expectation");

        deadlineExpectationTextfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        formNoteLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        formNoteLabel.setText("<html>Asterixed (<span style=\"color:red\">*</span>) fields are mandatory</html>");

        addTaskToDocButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addTaskToDocButton.setText(">>");
        addTaskToDocButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        docidLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        docidLabel.setText("DOC ID");

        datesignedLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        datesignedLabel.setText("Date Signed");
        datesignedLabel.setToolTipText("Time tracking begins. You may set this later.");

        datesignedDayTextfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        datesignedMonthCombobox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        datesignedMonthCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        datesignedYearCombobox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        datesignedYearCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        timeopenedMinutesTextfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        deadlineMinutesTextfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        taskdetailsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        taskdetailsLabel.setText("Task Details");

        taskTextArea.setColumns(20);
        taskTextArea.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        taskTextArea.setRows(5);
        taskTextAreaScrollPane.setViewportView(taskTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(referencenumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectTextfield)
                            .addComponent(referencenumberTextfield)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formNoteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(docidLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(responsibilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taskLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taskTextAreaScrollPane)
                            .addComponent(responsiblityCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deadlineExpectationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deadlineExpectationTextfield))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(datesignedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(datesignedDayTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datesignedMonthCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(datesignedYearCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(taskdetailsLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeopendLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deadlineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(deadlineDayTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(deadlineMonthCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(deadlineYearCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(timeopenedDayTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(timeopenedMonthCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(timeopenedYearCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(timeopenedHoursTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deadlineHoursTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(timeopenedMinutesTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deadlineMinutesTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeopendHoursLabel)
                                    .addComponent(timeopendDeadlineLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addTaskAndDocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addTaskToDocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cleartaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(formNoteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(docidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(referencenumberTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(referencenumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(datesignedDayTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(datesignedMonthCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(datesignedYearCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(datesignedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskdetailsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(taskLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(taskTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(responsibilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(responsiblityCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeopenedHoursTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeopendHoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeopenedMinutesTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deadlineHoursTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeopendDeadlineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deadlineMinutesTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timeopendLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deadlineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeopenedDayTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeopenedMonthCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeopenedYearCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deadlineDayTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deadlineMonthCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deadlineYearCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deadlineExpectationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deadlineExpectationTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTaskAndDocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cleartaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTaskToDocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTaskAndDocButton;
    private javax.swing.JButton addTaskToDocButton;
    private javax.swing.JButton cleartaskButton;
    private javax.swing.JTextField datesignedDayTextfield;
    private javax.swing.JLabel datesignedLabel;
    private javax.swing.JComboBox<String> datesignedMonthCombobox;
    private javax.swing.JComboBox<String> datesignedYearCombobox;
    private javax.swing.JTextField deadlineDayTextfield;
    private javax.swing.JLabel deadlineExpectationLabel;
    private javax.swing.JTextField deadlineExpectationTextfield;
    private javax.swing.JTextField deadlineHoursTextfield;
    private javax.swing.JLabel deadlineLabel;
    private javax.swing.JTextField deadlineMinutesTextfield;
    private javax.swing.JComboBox<String> deadlineMonthCombobox;
    private javax.swing.JComboBox<String> deadlineYearCombobox;
    private javax.swing.JLabel docidLabel;
    private javax.swing.JLabel formNoteLabel;
    private javax.swing.JLabel referencenumberLabel;
    private javax.swing.JTextField referencenumberTextfield;
    private javax.swing.JLabel responsibilityLabel;
    private javax.swing.JComboBox<String> responsiblityCombobox;
    private javax.swing.JSeparator separator;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JTextField subjectTextfield;
    private javax.swing.JLabel taskLabel;
    private javax.swing.JTextArea taskTextArea;
    private javax.swing.JScrollPane taskTextAreaScrollPane;
    private javax.swing.JLabel taskdetailsLabel;
    private javax.swing.JLabel timeopendDeadlineLabel;
    private javax.swing.JLabel timeopendHoursLabel;
    private javax.swing.JLabel timeopendLabel;
    private javax.swing.JTextField timeopenedDayTextfield;
    private javax.swing.JTextField timeopenedHoursTextfield;
    private javax.swing.JTextField timeopenedMinutesTextfield;
    private javax.swing.JComboBox<String> timeopenedMonthCombobox;
    private javax.swing.JComboBox<String> timeopenedYearCombobox;
    // End of variables declaration//GEN-END:variables

    public JButton getAddTaskAndDocButton() {
        return addTaskAndDocButton;
    }

    public JButton getAddTaskToDocButton() {
        return addTaskToDocButton;
    }

    public JButton getCleartaskButton() {
        return cleartaskButton;
    }

    public JTextField getDeadlineDayTextfield() {
        return deadlineDayTextfield;
    }

    public JTextField getDeadlineHoursTextfield() {
        return deadlineHoursTextfield;
    }

    public JLabel getDeadlineLabel() {
        return deadlineLabel;
    }

    public JComboBox<String> getDeadlineMonthCombobox() {
        return deadlineMonthCombobox;
    }

    public JComboBox<String> getDeadlineYearCombobox() {
        return deadlineYearCombobox;
    }

    public JLabel getDocidLabel() {
        return docidLabel;
    }

    public JLabel getReferencenumberLabel() {
        return referencenumberLabel;
    }

    public JTextField getReferencenumberTextfield() {
        return referencenumberTextfield;
    }

    public JLabel getResponsibilityLabel() {
        return responsibilityLabel;
    }

    public JComboBox<String> getResponsiblityCombobox() {
        return responsiblityCombobox;
    }

    public JLabel getSubjectLabel() {
        return subjectLabel;
    }

    public JTextField getSubjectTextfield() {
        return subjectTextfield;
    }

    public JLabel getTaskLabel() {
        return taskLabel;
    }

    public JSeparator getSeparator() {
        return separator;
    }

    public JTextArea getTaskTextArea() {
        return taskTextArea;
    }

    public JLabel getTaskdetailsLabel() {
        return taskdetailsLabel;
    }

    public JLabel getTimeopendLabel() {
        return timeopendLabel;
    }

    public JTextField getTimeopenedDayTextfield() {
        return timeopenedDayTextfield;
    }

    public JTextField getTimeopenedHoursTextfield() {
        return timeopenedHoursTextfield;
    }

    public JComboBox<String> getTimeopenedMonthCombobox() {
        return timeopenedMonthCombobox;
    }

    public JComboBox<String> getTimeopenedYearCombobox() {
        return timeopenedYearCombobox;
    }

    public JLabel getDeadlineExpectationLabel() {
        return deadlineExpectationLabel;
    }

    public JTextField getDeadlineExpectationTextfield() {
        return deadlineExpectationTextfield;
    }

    public JLabel getFormNoteLabel() {
        return formNoteLabel;
    }

    public JLabel getTimeopendDeadlineLabel() {
        return timeopendDeadlineLabel;
    }

    public JLabel getTimeopendHoursLabel() {
        return timeopendHoursLabel;
    }

    public JTextField getDatesignedDayTextfield() {
        return datesignedDayTextfield;
    }

    public JLabel getDatesignedLabel() {
        return datesignedLabel;
    }

    public JComboBox<String> getDatesignedMonthCombobox() {
        return datesignedMonthCombobox;
    }

    public JComboBox<String> getDatesignedYearCombobox() {
        return datesignedYearCombobox;
    }

    public JTextField getDeadlineMinutesTextfield() {
        return deadlineMinutesTextfield;
    }

    public JTextField getTimeopenedMinutesTextfield() {
        return timeopenedMinutesTextfield;
    }

    public JScrollPane getTaskTextAreaScrollPane() {
        return taskTextAreaScrollPane;
    }
}
